version: "3"

vars:
  user:
    sh: whoami
  hostname:
    sh: hostname

tasks:
  show:
    silent: true
    cmds:
      - cmd: nix flake show

  check:
    silent: true
    cmds:
      - cmd: nix flake check

  format:
    silent: true
    cmds:
      - cmd: alejandra . --quiet

  switch:
    silent: true
    cmds:
      - cmd: sudo nixos-rebuild switch --flake .#{{.hostname}}

  hm-switch:
    silent: true
    cmds:
      - cmd: home-manager switch --flake .#{{.user}}@{{.hostname}}

  switch-to:
    silent: true
    cmds:
      - cmd: sudo nixos-rebuild switch --flake .#{{ .CLI_ARGS }}

  test-switch:
    silent: true
    cmds:
      - cmd: sudo nixos-rebuild test --flake .

  garbage-collect:
    silent: true
    cmds:
      - cmd: sudo nix-collect-garbage --delete-older-than 1d
      - cmd: nix-collect-garbage --delete-older-than 1d

  update-flakes:
    silent: true
    cmds:
      - cmd: nix flake update
