version: "3"

tasks:
  show:
    cmds:
      - silent: true
        cmd: nix flake show

  check:
    cmds:
      - silent: true
        cmd: nix flake check

  format:
    cmds:
      - silent: true
        cmd: alejandra . --quiet

  switch:
    cmds:
      - silent: true
        cmd: sudo nixos-rebuild switch --flake .

  switch-to:
    cmds:
      - silent: true
        cmd: sudo nixos-rebuild switch --flake .#{{ .CLI_ARGS }}

  test-switch:
    cmds:
      - silent: true
        cmd: sudo nixos-rebuild test --flake .

  garbage-collect:
    cmds:
      - silent: true
        cmd: sudo nix-collect-garbage --delete-older-than 1d
      - silent: true
        cmd: nix-collect-garbage --delete-older-than 1d

  update-flakes:
    cmds:
      - silent: true
        cmd: nix flake update
