version: "3"
silent: true

vars:
  USER:
    sh: whoami
  HOSTNAME:
    sh: hostname

tasks:
  show:
    cmds:
      - cmd: nix flake show

  check:
    cmds:
      - cmd: nix flake check

  format:
    cmds:
      - cmd: alejandra . --quiet

  switch:
    cmds:
      - cmd: sudo nixos-rebuild switch --flake .#{{.HOSTNAME}}

  hm-switch:
    cmds:
      - cmd: home-manager switch --flake .#{{.USER}}@{{.HOSTNAME}}

  switch-to:
    cmds:
      - cmd: sudo nixos-rebuild switch --flake .#{{ .CLI_ARGS }}

  test-switch:
    cmds:
      - cmd: sudo nixos-rebuild test --flake .

  garbage-collect:
    cmds:
      - cmd: sudo nix-collect-garbage --delete-older-than 1d
      - cmd: nix-collect-garbage --delete-older-than 1d

  update-flakes:
    cmds:
      - cmd: nix flake update

  vscode-settings:
    cmds:
      - nix eval --json --impure .#homeConfigurations."{{.USER}}@{{.HOSTNAME}}".config.programs.vscode.profiles.default.userSettings

  repl:
    cmds:
      - nix repl --expr '{user = (builtins.getFlake (toString ./.)).homeConfigurations."{{.USER}}@{{.HOSTNAME}}";host = (builtins.getFlake (toString ./.)).nixosConfigurations.{{.HOSTNAME}};}'
