version: "3"

tasks:
  show:
    cmds:
      - silent: true
        cmd: nix flakes show

  format:
    cmds:
      - silent: true
        cmd: alejandra . --quiet

  switch:
    cmds:
      - silent: true
        cmd: sudo nixos-rebuild switch --flake .

  switch-to:
    cmds:
      - silent: true
        cmd: sudo nixos-rebuild switch --flake .#{{ .CLI_ARGS }}
