# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.loader.systemd-boot.enable = true;

  fileSystems."/" =
    { device = "/dev/mapper/luks-5c3f6163-bf1d-42fc-9ffe-e69dfe679ad4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5c3f6163-bf1d-42fc-9ffe-e69dfe679ad4".device = "/dev/disk/by-uuid/5c3f6163-bf1d-42fc-9ffe-e69dfe679ad4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FA55-B32B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-aea74856-1276-49bb-9b6b-f8c8415566ac"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
